start bsync function to synchronise binders, fix n2t rollout check_minders to properly copy minters

diff --git a/admegn b/admegn
--- a/admegn
+++ b/admegn
@@ -989,6 +989,45 @@ function msync {
 	#)" | admegn mload ~/sv/cur/apache2/minters
 }
 
+# sync (update) local binders to catch up with source state of remote binders
+
+function bsync {
+
+	local ruserhost=${1:-}
+	[[ ! "$ruserhost" ]] && {
+		echo "Error: no remote host specified" 1>&2
+		return 1
+	}
+#my $rwind = '^==* report window .* to \([0-9].*\)$';
+#my $changed_ids = `tlog --mods $changetime $td/logs/transaction_log \\
+#        | sed -n -e 's/^.=mod== [^ ][^ ]* //p' -e 's/$rwind/# end: \\1/p'`;
+#
+#my $report_end_time;    # in practice, a tlog parameter for next harvest
+#$changed_ids =~ s/^# end: (.*)\n// and
+#        $report_end_time = $1;
+#like $report_end_time, qr/^\d\d\d\d\.\d\d\.\d\d\_\d\d:\d\d:\d\d\.?\d*$/,
+#        "report end time captured";
+
+
+# XXX big question? can the iddump stuff run from a non-installed egg?
+#     ie, running under perl -Mblib from an eggnogALT directory?
+	#ssh $ruserhost "(
+	#	cd ~/sv/cur/apache2/eggnogALT ?
+	#	starttime=$( cat NEXT_HARVEST_START )
+	# XXX make sure log rotation is temporarily off(?)
+	#	tlog --mods $starttime $sa/logs/transaction_log \
+	#	   sed ... to filter changes and save new NEXT_HARVEST_START
+	#	   create > ezid.changed_ids
+	#	   create > oca.changed_ids
+	#	altegg iddump $sa/binders/ezid < ezid.changed_ids |
+	#		ssh xxx "(idload $sa/binders/...ezid_s_ezid
+	#	altegg iddump $sa/binders/oca < oca.changed_ids
+	#		ssh xxx "(idload $sa/binders/...oca_s_oca
+	#)"
+
+	# run this every 10 mins?
+}
+
 # these sources usually overridden during pfx validation
 #
 ShouldersFile=~/shoulders/master_shoulders.txt	# default
diff --git a/n2t b/n2t
--- a/n2t
+++ b/n2t
@@ -165,37 +165,35 @@ function check_default_binders {
 
 function check_minders {
 
-	for m in binders minters shoulders
-	do
-		# Don't want to overwrite any existing binders, but we want
-		# make sure (eg, first time deploy ever on new system) that
-		# at least some binders are in place (that's what
-		# check_default_binders is for). Regarding minters and
-		# shoulders, we don't copy in anything if there's already a
-		# minters (shoulders) directory, but for the first time, we
-		# do copy in fresh defaults.
+	# Do binders.
+	# Don't want to overwrite any existing binders, but we want make sure
+	# (eg, first time deploy ever on new system) that at least some
+	# binders are in place (that's what check_default_binders is for).
 
-		if [[ "$m" == 'binders' ]]
-		then
-			mkdir -p $aptop/$m
-			check_default_binders $m	# not checking return
+	mkdir -p $aptop/binders
+	check_default_binders binders	# not checking return
+
+	# Do shoulders.
+
+	mkdir -p $aptop/shoulders	# yyy incomplete
+
+	# Do minters.
+	# Don't copy in anything if there's already a minter directory, but
+	# the first time seeing a new populator, we do copy in fresh defaults.
+
+	local populator dstpopulator
+	for m in $nsf/minters/*
+	do
+		populator=$( basename $m )
+		dstpopulator=$aptop/minters/$populator
+		[[ -e $dstpopulator ]] &&
 			continue
-		elif [[ -e $aptop/$m ]]
-		then
-			continue	# already there, don't need to create
-		fi
-		## if we get here, there's a missing directory
-		#read -t 30 -p \
-		#	"Server has no $m directory.  Create? [Y/n] "
-		#	# Y is default.
-		#[[ $? != 0 ]] && {
-		#	echo -e "\nError: response EOF or timeout: aborting."
-		#	exit 1
-		#}
-		#[[ $REPLY == "" || $REPLY =~ ^[yY] ]] ||
-		#	continue
-		cp -pr $nsf/$m $aptop
-		echo Initializing directory: $aptop/$m
+		echo Initializing directory: $dstpopulator
+		mkdir $dstpopulator || {
+			echo "Error: panic -- don't want to overwrite minters"
+			exit 1		# since no one checks our return status
+		}
+		cp -pr $m $aptop/minters/
 	done
 }
 
