fix binder_load and backup rotation given new binder naming scheme

diff --git a/admegn b/admegn
--- a/admegn
+++ b/admegn
@@ -20,7 +20,7 @@ function usage {
 
 summary="
      $me warts
-     $me binder_load Dbdir < db_dump_file
+     $me binder_load Dbdir Dbdump_file
      $me msync RemoteHost
        $me mdump [ -v ] [ Minter/nog.bdb ... ] [ > MinterStates ]
        $me mload [ -nv ] Dir [ < MinterStates ]
@@ -70,9 +70,13 @@ DESCRIPTION
 
        If you don't clean up the remote \$dbdir directory beforehand by
        removing any __db.* and/or log.* files, bad things can happen when
-       they interfere with the new environment. Also, you could try
+       they interfere with the new environment. Also, bad might happen if
+       you're loading a new binder that will be used as it is appearing,
+       so you might want to turn off apache.
 
-        \$ ssh \$rhost "admegn binder_load \$dbdir < db_dump_file"
+       Also, you could have the dump file locally and just call
+
+        \$ admegn binder_load \$dbdir db_dump_file
 
        XXX needed?
        The "warts" form takes the ~/warts/env.sh bash scripts and creates a
@@ -918,21 +922,45 @@ EOT
 function binder_load {
 
 	local dbdir=${1:-}
+	local dbdump=${2:-}
 	[[ ! "$dbdir" ]] && {
 		echo "Error: no binder directory specified" 1>&2
 		return 1
 	}
-	( cd $dbdir
-		rm -f log.* __db.*
-		local envfiles
-		envfiles=$( ls log.* __db.* | grep -v '\*' )
-		[[ "$envfiles" ]] &&  {
-			echo Error: some env files still exist: log.* __db.*
-			return 1
-		}
-		db_load egg.bdb
-		#TMPDIR=~/backups db_load egg.bdb
-	)
+	[[ ! "$dbdump" ]] && {
+		echo "Error: no binder dump specified" 1>&2
+		return 1
+	}
+
+	cd $dbdir/..
+	local sbdr=$( basename $dbdir )		# short binder name
+	if [[ -e $sbdr ]]
+	then
+		mv $sbdr OLD$sbdr
+		mkdir $sbdr
+		# copy back binder infrastructure files minus log.* and __db.*
+		#cp -p OLD$sbdr/{0=egg_1.00,0=pairtree_1.02,egg.rlog} $sbdr
+		#cp -pr OLD$sbdr/{egg_lock,egg_README,pairtree_root} $sbdr
+		local files=(
+			OLD$sbdr/{0=egg_1.00,0=pairtree_1.02,egg.rlog}
+			OLD$sbdr/{egg_lock,egg_README,pairtree_root}
+		)
+		for f in "${files[@]}"
+		do
+			[[ ! -e $f ]] &&
+				continue
+			cp -pr $f $sbdr
+		done
+		#cp -pr OLD$sbdr/{egg_lock,egg_README,pairtree_root} $sbdr
+	else
+		mkdir $sbdr
+	fi
+	local tail=$( basename $dbdump )	# hopefully timestamped name
+	date > $sbdr/FROM_BACKUP_$tail
+
+	cd $sbdr;
+	db_load egg.bdb < $dbdump
+	# NB: make sure TMPDIR env var is other than /
 }
 
 # sync local minters up from remote state
@@ -1200,8 +1228,10 @@ expected: $t
 	}
 	[[ "$msg" ]] && {
 		local subject="resolver health check report"
-		[[ $errcnt -gt 0 ]] &&
-			subject="CRITICAL: $errcnt resolver errors"
+		[[ $errcnt -gt 0 ]] && {
+			local sname=$( egg --home $ap_top cfq shell_name )
+			subject="CRITICAL: $sname: $errcnt resolver errors"
+		}
 		mail -s "$subject" $notify <<< "$msg"
 	}
 	[[ $errcnt -eq 0 ]] &&
@@ -1709,24 +1739,25 @@ function backup {
 	do
 		b=$( basename $binder )
 		#[[ $b =~ _test$ || ! -e ~/binders/$b/egg.bdb ]] &&	# skip
-		[[ $b =~ _test$ || ! -e $apbinders/$b/egg.bdb ]] &&	# skip
-			continue	# if not a binder or not a real binder
+		[[ $b =~ _test$ || $b =~ _old$ ||	# skip these and dirs
+		    ! -e $apbinders/$b/egg.bdb ]] &&	# w.o. real binders
+			continue
 
-		# In order to run egg against a backup binder, and because of
-		# how egg requires long ugly binder names in anticipation of
-		# flatter database-server-based binder access (instead of tidy
-		# short names made unique by file hierarchy), we need the
-		# long binder name to be the final path component before the
-		# egg.bdb file. The awkward consequence is that the timestamp
-		# file path component precedes it.
+		# In order to be able to run egg against a backup binder,
+		# and because of how egg requires long ugly binder names in
+		# anticipation of flatter database-server-based binder access
+		# (instead of tidy short names made unique by file hierarchy),
+		# we need the long binder name to be the final path component
+		# before the egg.bdb file. The awkward consequence is that the
+		# binder names both the parent and a chile of the timestamped
+		# backup directory.
 
 		#src=~/binders/$b
 		src=$apbinders/$b
-		dst=~/backups/binders/$now/$b
+		dst=~/backups/binders/$b/$now/$b
 		#dst=~/backups/binders/$b/$now
 		mkdir -p $dst
 		echo Running: db_hotbackup -h $src -b $dst
-		echo "XXX  TMPDIR: $TMPDIR"
 		db_hotbackup -h $src -b $dst
 		#took=$( ( time db_hotbackup -h $src -b $dst ) 2>&1 )
 		#echo " " $( sed -n s/real//p <<< "$took" )
@@ -1738,11 +1769,14 @@ function backup {
 	do
 		b=$( basename $binder )
 		#[[ $b =~ _test$ || ! -e ~/binders/$b/egg.bdb ]] &&	# skip
-		[[ $b =~ _test$ || ! -e $apbinders/$b/egg.bdb ]] &&	# skip
-			continue	# if not a binder or not a real binder
+		[[ $b =~ _test$ || $b =~ _old$ ||	# skip these and dirs
+		    ! -e $apbinders/$b/egg.bdb ]] &&	# w.o. real binders
+			continue
+		#[[ $b =~ _test$ || ! -e $apbinders/$b/egg.bdb ]] &&	# skip
+		#	continue	# if not a binder or not a real binder
 		#dst=~/backups/binders/$b/$now
-		dst=~/backups/binders/$now/$b
-		echo Running db_verify for $b: db_verify $dst/egg.bdb
+		dst=~/backups/binders/$b/$now/$b
+		echo Running: db_verify $dst/egg.bdb
 		#msg=$( time db_verify $dst/egg.bdb 2>&1 ) || {
  		msg=$( db_verify $dst/egg.bdb 2>&1 ) || {
 			echo "$msg" > $dst/VERIFY_FAILED
@@ -1750,7 +1784,7 @@ function backup {
 			echo "$msg"
 			mail -s "$b binder backup (removed) failed db_verify" \
 				$notify <<< "$msg"
-			rm -fr $dst		# toss -- backup not useful
+			rm -fr $dst/..		# toss -- backup not useful
 			continue		# don't fall through
 		}
 
@@ -1769,6 +1803,7 @@ function backup {
 # an integer, max, defining the maximum number that you want to keep,
 # and a directory, dst (usually ending in "weeklies" or "monthlies"),
 # to move the surplus to.
+#
 # Assumes backups live in timestamped subdirs of src and dst.
 
 # If 7th day, move 1 surplus backup to tier 2
@@ -1776,7 +1811,7 @@ function backup {
 # 		Remove any surplus tier 3 backups
 # 	Remove surplus tier 2 backups
 # Remove surplus tier 1 backups
-#
+
 function surplus {
 
 	local cmd=$1
@@ -1817,6 +1852,8 @@ function surplus {
 	done
 }
 
+# Strip surplus. Args say when and how many files to keep of each tier type.
+#
 # Usage: splus \
 #	tier1 t1max t12cond \
 #	tier2 t2max t23cond \
@@ -1832,7 +1869,7 @@ function surplus {
 #	    $ splus	$b           10 $day7th \
 #		        $b/weeklies  4  $day28th \
 #		        $b/monthlies 4
-#
+
 function splus {
 
 	local t1bax=$1		# tier1 backups directory
@@ -1892,6 +1929,7 @@ function backup_rotate {
 		[[ ! -e $apbinders/$( basename $bbk )/egg.bdb ]] &&
 			continue	# not a binder -- skip
 
+		# keep 14 dailies, 4 weeklies, 4 monthlies
 		splus	$bbk           14 	$day7th \
 		        $bbk/weeklies   4  	$day28th \
 		        $bbk/monthlies  4
