add cert_check to admegn and crontab; fix error detetection during pfx harvest

diff --git a/pfx b/pfx
--- a/pfx
+++ b/pfx
@@ -396,6 +396,8 @@ function pfx_harvest_validate {
 	# yyy adding naan_table.txt to make it easy to grep for NAANs
 	for f in $pfx_base naan_table.txt ${pfx_sources[@]}
 	do
+		[[ ! -f "$pfx_quarantine/$f" ]] &&	# if expected file
+			continue	# doesn't exist, ignore it (yyy ok?)
 		[[ $pfx_harvest/$f -nt $pfx_quarantine/$f && ! "$force" ]] &&
 			continue		# yyy emit message here?
 		# xxx for now there's no check other than for zero size
@@ -483,12 +485,16 @@ EOT
 
 function pfx_harvest {
 
-	[[ ! -d $pfx_quarantine ]] && {
+	# Make sure quarantine directory exists and is empty.
+	if [[ ! -d $pfx_quarantine ]]
+	then
 		mkdir -p $pfx_quarantine || {
 			echo "error: couldn't create $pfx_quarantine" 1>&2
 			return 1
 		}
-	}
+	else
+		rm -f $pfx_quarantine/*
+	fi
 	local n=0		# number of files imported yyy needed?
 
 	# Assume current dir is $pfx_build. xxx needed?
@@ -526,7 +532,7 @@ function pfx_harvest {
 	#scp -qp $pfx_maint_host:"$rfiles" $pfx_quarantine || 
 	local rfiles=
 # XXX this must be tested in production
-	local rfile
+	local rfile lfile		# remote and local file
 	local maint_service=https://n2t.net/e/pub
 	# yyy adding naan_table.txt to make it easy to grep for NAANs
 	for rfile in naan_registry.txt shoulder_registry.txt master_shoulders.txt lsregistry.yml naan_table.txt
@@ -534,7 +540,7 @@ function pfx_harvest {
 		wget -q -O $pfx_quarantine/$rfile $maint_service/$rfile || {
 			echo "Error running wget -q -O $pfx_quarantine/$rfile" \
 				"$maint_service/$rfile" 1>&2
-			return 1
+			return 1	# Important source - abort on error
 		}
 	done
 	# kludge to rename!
@@ -552,15 +558,21 @@ function pfx_harvest {
 	cp ~/n2t_create/ebireg.xml $pfx_quarantine	# XXX kludge
 
 	ebi_newurl='https://registry.api.identifiers.org/resolutionApi/getResolverDataset'
-	wget -q -O $pfx_quarantine/ebinewreg.json $ebi_newurl || {
+	lfile="$pfx_quarantine/ebinewreg.json"
+	wget -q -O $lfile $ebi_newurl || {
 		echo "Error running wget from $ebi_newurl" 1>&2
-		return 1
+		rm -f $lfile
+		# less important source, report error and proceed
+		# return 1
 	}
 
 	prefixcc_url='http://prefix.cc/popular/all.file.json'
-	wget -q -O $pfx_quarantine/prefixcc.json $prefixcc_url || {
+	lfile="$pfx_quarantine/prefixcc.json"
+	wget -q -O $lfile $prefixcc_url || {
 		echo "Error running wget from $prefixcc_url" 1>&2
-		return 1
+		rm -f $lfile
+		# less important source, report error and proceed
+		# return 1
 	}
 
 	pfx_harvest_validate ||	# if ok, moves files up out of quarantine
